version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: gofortickets
    ports:
     - 5432:5432
    volumes:
    - ./create.sql:/docker-entrypoint-initdb.d/create.sql 
